//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramOrgApp.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DozzierOCEntities : DbContext
    {
        public DozzierOCEntities()
            : base("name=DozzierOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dependencia> Dependencia { get; set; }
        public virtual DbSet<Directorio> Directorio { get; set; }
        public virtual DbSet<Elemento> Elemento { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Funcion> Funcion { get; set; }
        public virtual DbSet<Organizacion> Organizacion { get; set; }
        public virtual DbSet<OrgchartUser> OrgchartUser { get; set; }
        public virtual DbSet<TipoElemento> TipoElemento { get; set; }
        public virtual DbSet<TipoIdentificacion> TipoIdentificacion { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
