//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiagramOrgApp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int pk_Usuario { get; set; }
        public int fk_Directorio { get; set; }
        public string loginUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public string emailUsuario { get; set; }
    
        public virtual Directorio Directorio { get; set; }
    }
}
